$schema: "https://moonrepo.dev/schemas/tasks.json"

fileGroups:
  cargo:
    - "Cargo.toml"
    - "src/**/*"
  sources: []
  tests:
    - "benches/**/*"
    - "tests/**/*"

tasks:
  fetch:
    command: "cargo fetch"
    inputs:
      - "Cargo.toml"
      - "**/Cargo.toml"
      - "Cargo.lock"
    env: *env

  build:
    <<: *build
    deps:
      - "~:fetch"

  check:
    command: "cargo check --all-targets"
    inputs:
      - "@group(cargo)"
      - "@group(sources)"
      - "@group(tests)"
    deps:
      - "~:fetch"
    env: *env

  lint:
    command: "cargo clippy --all-targets"
    inputs:
      - "@group(cargo)"
      - "@group(sources)"
      - "@group(tests)"
      - "/.clippy.toml"
    deps:
      - "~:fetch"
    env: *env

  test:
    command: "cargo nextest run --no-fail-fast -p solidus-$project"
    inputs:
      - "@group(cargo)"
      - "@group(sources)"
      - "@group(tests)"
      - "/.config/nextest.*"
      - "fuzz/regressions/**/*"
    deps:
      - "~:fetch"
    env: *env
