name: Deploy

on:
  push:
    branches: [main]
    paths:
      - "website/**"

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: ./.github/actions/moon-setup
        with:
          rust: "false"
      - run: moon run website:deploy
