# .github/workflows/publish-wasm.yml
name: Publish WASM + WIT

on:
  release:
    types: [published]

jobs:
  publish-wasm-javascript:
    if: startsWith(github.event.release.tag_name, 'wasm-javascript-v')
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write
    steps:
      - uses: ./.github/actions/setup
        with:
          cache-cargo: "true"

      - name: Build wasm-javascript
        run: moon run wasm-javascript:build

      - name: Attach artifacts to GitHub Release
        run: ./wasm-javascript/scripts/attach-release-assets.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-wasm-wasi:
    if: startsWith(github.event.release.tag_name, 'wasm-wasi-v')
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write
    steps:
      - uses: ./.github/actions/setup
        with:
          cache-cargo: "true"

      - name: Build wasm-wasi + WIT
        run: moon run wasm-wasi:build

      - name: Attach wasm-wasi and WIT artifacts to GitHub Release
        run: ./wasm-wasi/scripts/attach-release-assets.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
