# .github/workflows/publish-riff.yml
name: Publish riff

on:
  release:
    types: [published]

jobs:
  publish:
    if: startsWith(github.event.release.tag_name, 'riff-cli-v')
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write
      packages: write
    steps:
      - uses: ./.github/actions/setup
        with:
          cache-cargo: "true"

      - name: Run riff publish (GoReleaser)
        run: moon run riff-cli:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
