# .github/workflows/publish-npm-slash-web.yml
name: Publish @slasher/slash-web

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/publish-to-registry.yml
    with:
      tag-prefix: "slash-web-v"
      moon-task: "slash-web:publish"
      cache-pnpm: true
      needs-oidc: true
    secrets: inherit
