# .github/workflows/publish-crates.yml
name: Publish crates

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/publish-to-registry.yml
    with:
      tag-prefix: "slash-rust-v"
      moon-task: "slash-rust:publish"
      cache-cargo: true
    secrets: inherit
