# .github/workflows/publish-npm-slash-javascript.yml
name: Publish @slasher/slash-javascript

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/publish-to-registry.yml
    with:
      tag-prefix: "slash-javascript-v"
      moon-task: "slash-javascript:publish"
      cache-pnpm: true
      needs-oidc: true
    secrets: inherit
