name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Affected
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: ./.github/actions/moon-setup
        with:
          go: "true"
          python: "true"

      - run: moon run :publish --affected
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.event.release.tag_name }}

      - name: Attach artifacts to release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          if [ -d dist/ ]; then
            gh release upload "$TAG" dist/* --clobber
          fi
