# .github/workflows/publish-pypi.yml
name: Publish slash-python

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/publish-to-registry.yml
    with:
      tag-prefix: "slash-python-v"
      moon-task: "slash-python:publish"
    secrets: inherit
